### PR TITLE
[MOD] Upgrade Docker and docker-compose to most recent

### PR DESCRIPTION
**Pull request by ovcharenko**
Any obstacles for such upgrade?

### CODE REVIEW

**Review by yob — COMMENTED** [review]
The docker-compose change is definitely uncontroversial.

There has been some discussion in #792 about whether upgrading docker might be a breaking change that should wait for a 6.0 release. I don't think we know enough about the 19.03 to 20.10 upgrade to answer that yet - do you feel across how compatible this would be for all users of the stack?

**Comment by ovcharenko** [comment]
> The docker-compose change is definitely uncontroversial.
> 
> There has been some discussion in #792 about whether upgrading docker might be a breaking change that should wait for a 6.0 release. I don't think we know enough about the 19.03 to 20.10 upgrade to answer that yet - do you feel across how compatible this would be for all users of the stack?

We didn't notice any downside on our projects. But still asking community for possible cases...

**Comment by chloeruka** [comment]
There's an apple silicon compatibility note in 20.10.6 that might make that worth considering over 20.10.4

**Comment by yob** [comment]
Apologies @ovcharenko applying these upgrades on master, but over in #825 and #826. The main difference on those PRs is applying matching upgrades to our windows AMIs.

Thanks for the nudge to get it done though :heart: 

 The upgrades are included in 5.3.0.

**Pull request closed without merging**
