### PR TITLE
Support for setting EbsOptimzed

### PR DESCRIPTION
**Pull request by peter-svensson**

### CODE REVIEW

**Comment by ecv** [comment]
This may what I need to launch c6g and r6g instances. ('Requested configuration not supported' at present; console not being clear, and I haven't tested with this branch yet, but.)

Either way, me gusta.

**Comment by nitrocode** [comment]
@chloeruka friendly ping :)

**Comment by lox** [comment]
I recall looking at this several years ago and my conclusion was that newer instance types had this automatically enabled: 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html

Has anything changed since then that would make manually enabling this useful? 🤔

**Comment by nitrocode** [comment]
That's a good point. Looks like ebs optimization is enabled for arm instance types (c6g, r6g) that @ecv mentioned.

**Comment by yob** [comment]
Thanks for triggering this discussion @peter-svensson.

Our understanding is that this is enabled automatically depending on the instance type so we'll close it. If we're wrong (or the issue is more nuanced than we realised) we're happy to re-open though!

**Comment by peter-svensson** [comment]
I just tested this today

```
aws cloudformation create-stack \
  --output text \
  --stack-name buildkite \
  --template-url "https://s3.amazonaws.com/buildkite-aws-stack/latest/aws-stack.yml" \
  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
  --parameters "$(cat config.json)"```

```cat config.json                                             
[
  {
    "ParameterKey": "BuildkiteAgentToken",
    "ParameterValue": "123"
  },
  {
    "ParameterKey": "KeyName",
    "ParameterValue": "peter"
  },
  {
    "ParameterKey": "InstanceType",
    "ParameterValue": "m5.large"
  }
]```

This results in a launch-configuration that creates EC2 instance with:

<img width="1039" alt="Screen Shot 2020-09-15 at 12 36 18" src="https://user-images.githubusercontent.com/378483/93200484-192c4f00-f750-11ea-8dcb-0dea1d273183.png">


So it looks like the EBS optimisation is not set to `true`, which seems to be inline with the documentation for [Cloudformation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-ebsoptimized):

```EbsOptimized
Indicates whether the instance is optimized for Amazon EBS I/O. This optimization provides dedicated throughput to Amazon EBS and an optimized configuration stack to provide optimal Amazon EBS I/O performance. This optimization isn't available with all instance types. Additional usage charges apply when using an EBS-optimized instance.

Default: false

Required: No

Type: Boolean
```

If I create the same instance type (m5.large) in the AWS console I do get `EBSOptimized`  set to `true` as a default value.

Screen Shot 2020-09-15 at 12 38 33

So the documentation that you posted above @lox is correct for the console, but not for Cloudformation.

Feel free to test and verify yourselves.

I'd say this PR should still be valid and merged 😊

**Comment by yob** [comment]
Thanks for the deep dive @peter-svensson!

Confusingly, the [docs for ebs-optimized instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html) say:

> The following table lists the instance types that support EBS optimization and EBS optimization is enabled by default. There is no need to enable EBS optimization and no effect if you disable EBS optimization.

There's a small number of instance types further down the docs that have different behvaiour documented:

> The following table lists the instance types that support EBS optimization but EBS optimization is not enabled by default. You can enable EBS optimization when you launch these instances or after they are running. Instances must have EBS optimization enabled to achieve the level of performance described. When you enable EBS optimization for an instance that is not EBS-optimized by default, you pay an additional low, hourly fee for the dedicated capacity

The instance types in the second group mostly look old-ish. Is it possible the ebs-optimised flag you're seeing set (or not set) has no impact on the m5.large in your test?

We're not flat out opposed to adding this parameter, we're just aware that the stack is using 48/60 possible parameters so they're becoming a precious resource to use sparingly.

**Comment by peter-svensson** [comment]
> We're not flat out opposed to adding this parameter, we're just aware that the stack is using 48/60 possible parameters so they're becoming a precious resource to use sparingly.

@yob I totally agree on keeping the number of parameters down...

> The instance types in the second group mostly look old-ish. Is it possible the ebs-optimised flag you're seeing set (or not set) has no impact on the m5.large in your test?

The m5.large is not in the short list. It's in the top table with an asterisk on it and in the middle table

Instance size | Maximum bandwidth (Mbps) | Maximum throughput (MB/s, 128 KiB I/O) | Maximum IOPS (16 KiB I/O)
-- | -- | -- | --
m5.large * | 4,750 | 593.75 | 18,750

\* These instance types can support maximum performance for 30 minutes at least once every 24 hours. If you have a workload that requires sustained maximum performance for longer than 30 minutes, select an instance type according to baseline performance as shown in the following table.

Instance size | Baseline bandwidth (Mbps) | Baseline throughput (MB/s, 128 KiB I/O) | Baseline IOPS (16 KiB I/O)
-- | -- | -- | --
m5.large | 650 | 81.25 | 3,600


And just to check I set it up with an instancetype without asterisk (m5.4xlarge) and it is still not EBS optimized (from what the console shows) - haven't done any real I/O performance tests.

Screen Shot 2020-09-15 at 15 56 14

**Comment by lox** [comment]
@peter-svensson I believe that is just referring to burstable IOPS on the underlying EBS device isn't it? 

Perhaps we can check with AWS support @yob? Another option would be to always enable it.

**Comment by peter-svensson** [comment]
It's confusing enough alright 😊 
I don't think we can always enable it - instance that doesn't support it won't start if I remember correctly.
Checking with AWS would be a good thing I guess.

**Comment by yob** [comment]
Thanks for encouraging us to get to the bottom of this @peter-svensson.

I reached out to AWS support and got the following answer:

> I understand you want to confirm the impact of using EbsOptimized property of AWS::EC2::Instance in the cloudformation template with different types of instance types.
>
> Please correct me if my understanding is incorrect.
>
> Certain instances types are EBS optimized by default. There is no need to enable EBS optimization and no effect if you disable EBS optimization. Examples of such instances include m5.large and others from the table linked here under the section: [EBS optimized by default](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html#ebs-optimization-support).
>
> Then there are instances with support EBS optimization but EBS optimization is not enabled by default. You can enable EBS optimization when you launch these instances or after they are running [2]. List of such instances include m3.xlarge or r3.2xlarge and can be found here under the section: [EBS optimization supported](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html#ebs-optimization-support).
>
> In the CloudFormation template, enabling or disabling EbsOptimized property will have no effect on instances which are EBS optimized by default. However, this property can be used to enable EBS optimization for instances which do support EBS optimization but EBS optimization is not enabled by default.

Based on the answer, I see three obvious options:

1. Set `EbsOptimized` to true for everyone. In the majority of cases it'll have no effect, but teams using instance types like m3.xlarge or r3.2xlarge will get improved IO performance (for a cost)
2. Set `EbsOptimized` to false by default, but add the new parameter so teams using instance types like m3.xlarge or r3.2xlarge can opt to pay more for improved IO performance
3. Status-quo - we don't set `EbsOptimized`. There's no impact for most users of the stack, but anyone using instance types like m3.xlarge or r3.2xlarge have no ability to opt into paying for improved IO performance

I lose track of all the instance types and their background, but are all the instances that benefit from EBSOptimized ([the third table here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-optimized.html)) legacy generations? Looking at [these docs](https://aws.amazon.com/ec2/previous-generation/) it seems like they might be.

**Comment by nitrocode** [comment]
Thanks everyone for looking into this.

> Certain instances types are EBS optimized by default. There is no need to enable EBS optimization and no effect if you disable EBS optimization. Examples of such instances include m5.large and others from the table linked here under the section: EBS optimized by default.

That seems to conflict with @peter-svensson's m5.4xlarge where it's in the table to be ebs optimized by default yet the aws console shows that the ebs optimization is disabled...

**Comment by yob** [comment]
> That seems to conflict with @peter-svensson's m5.4xlarge where it's in the table to be ebs optimized by default yet the aws console shows that the ebs optimization is disabled...

My read is that the m5.4xlarge always has EBS Optimization, regardless of whether the flag in the console is on or off. I haven't verified that with benchmarks though.

**Comment by peter-svensson** [comment]
Sounds like it should be impossible to not enable it then 😊 
Could be that the AWS console (and possible AWS cli) returns the wrong value for `EbsOptimized`

I did a simple test today using [fio](https://fio.readthedocs.io/en/latest/) on two m5.4xlarge AWS instances. Both created from the buildkite launchconfiguration, one with `EBSOptimized`  (10-0-2-224) and one without (10-0-2-127).
Disclaimer: I have no experience or idea on how to do proper I/O testing what so ever...
Found some simple tests [here](https://docs.cloud.oracle.com/en-us/iaas/Content/Block/References/samplefiocommandslinux.htm)

If I interpret the results correctly:
* Random R/W latency test looks like it's performing around 30% better with EBS opimization flag turned on. 
* Random R/W more or less on par.

Would be great if someone who actually knows could verify and come up with a conclusion. 
From this test I'd say that the optimizaiton flag probably always is turned on and makes no difference to set it "manually"..


```
[ec2-user@ip-10-0-2-224 ~]$ fio fioradomrwlatency.fio
job1: (g=0): rw=randrw, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=1
fio-2.14
Starting 1 process
Jobs: 1 (f=1): [m(1)] [100.0% done] [4516KB/4656KB/0KB /s] [1129/1164/0 iops] [eta 00m:00s]
job1: (groupid=0, jobs=1): err= 0: pid=17112: Thu Sep 17 07:23:14 2020
  read : io=512576KB, bw=4271.5KB/s, iops=1067, runt=120001msec
    slat (usec): min=2, max=153, avg= 7.19, stdev= 2.93
    clat (usec): min=181, max=18302, avg=360.50, stdev=250.94
     lat (usec): min=188, max=18308, avg=367.91, stdev=251.05
    clat percentiles (usec):
     |  1.00th=[  207],  5.00th=[  217], 10.00th=[  227], 20.00th=[  239],
     | 30.00th=[  255], 40.00th=[  278], 50.00th=[  354], 60.00th=[  374],
     | 70.00th=[  394], 80.00th=[  414], 90.00th=[  446], 95.00th=[  524],
     | 99.00th=[ 1336], 99.50th=[ 1960], 99.90th=[ 3280], 99.95th=[ 3856],
     | 99.99th=[ 5728]
  write: io=515832KB, bw=4298.6KB/s, iops=1074, runt=120001msec
    slat (usec): min=2, max=87, avg= 8.03, stdev= 3.36
    clat (usec): min=388, max=18434, avg=552.28, stdev=291.51
     lat (usec): min=393, max=18442, avg=560.53, stdev=291.62
    clat percentiles (usec):
     |  1.00th=[  430],  5.00th=[  446], 10.00th=[  458], 20.00th=[  474],
     | 30.00th=[  486], 40.00th=[  502], 50.00th=[  516], 60.00th=[  532],
     | 70.00th=[  548], 80.00th=[  588], 90.00th=[  652], 95.00th=[  732],
     | 99.00th=[  988], 99.50th=[ 1208], 99.90th=[ 4768], 99.95th=[ 7456],
     | 99.99th=[11968]
    lat (usec) : 250=13.55%, 500=53.40%, 750=29.66%, 1000=2.17%
    lat (msec) : 2=0.86%, 4=0.27%, 10=0.08%, 20=0.01%
  cpu          : usr=1.14%, sys=2.54%, ctx=257297, majf=0, minf=11
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=128144/w=128958/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: io=512576KB, aggrb=4271KB/s, minb=4271KB/s, maxb=4271KB/s, mint=120001msec, maxt=120001msec
  WRITE: io=515832KB, aggrb=4298KB/s, minb=4298KB/s, maxb=4298KB/s, mint=120001msec, maxt=120001msec

Disk stats (read/write):
  nvme0n1: ios=128076/129841, merge=0/30, ticks=45360/70080, in_queue=596, util=0.23%
```

```
[ec2-user@ip-10-0-2-127 ~]$ fio fioradomrwlatency.fio
job1: (g=0): rw=randrw, bs=4K-4K/4K-4K/4K-4K, ioengine=libaio, iodepth=1
fio-2.14
Starting 1 process
Jobs: 1 (f=1): [m(1)] [100.0% done] [3412KB/3556KB/0KB /s] [853/889/0 iops] [eta 00m:00s]
job1: (groupid=0, jobs=1): err= 0: pid=18227: Thu Sep 17 07:14:51 2020
  read : io=382964KB, bw=3191.4KB/s, iops=797, runt=120001msec
    slat (usec): min=2, max=38, avg= 5.10, stdev= 1.92
    clat (usec): min=182, max=48211, avg=641.94, stdev=708.07
     lat (usec): min=188, max=48215, avg=647.19, stdev=708.10
    clat percentiles (usec):
     |  1.00th=[  211],  5.00th=[  227], 10.00th=[  247], 20.00th=[  370],
     | 30.00th=[  386], 40.00th=[  398], 50.00th=[  410], 60.00th=[  430],
     | 70.00th=[  470], 80.00th=[  636], 90.00th=[ 1432], 95.00th=[ 2128],
     | 99.00th=[ 3312], 99.50th=[ 3888], 99.90th=[ 5216], 99.95th=[ 5984],
     | 99.99th=[ 9664]
  write: io=386184KB, bw=3218.2KB/s, iops=804, runt=120001msec
    slat (usec): min=2, max=105, avg= 6.04, stdev= 2.50
    clat (usec): min=406, max=12694, avg=591.88, stdev=159.11
     lat (usec): min=411, max=12701, avg=598.06, stdev=159.25
    clat percentiles (usec):
     |  1.00th=[  446],  5.00th=[  466], 10.00th=[  478], 20.00th=[  498],
     | 30.00th=[  516], 40.00th=[  532], 50.00th=[  556], 60.00th=[  580],
     | 70.00th=[  612], 80.00th=[  668], 90.00th=[  748], 95.00th=[  836],
     | 99.00th=[ 1048], 99.50th=[ 1176], 99.90th=[ 1944], 99.95th=[ 2768],
     | 99.99th=[ 4768]
    lat (usec) : 250=5.31%, 500=41.91%, 750=38.83%, 1000=6.08%
    lat (msec) : 2=4.94%, 4=2.72%, 10=0.21%, 20=0.01%, 50=0.01%
  cpu          : usr=0.65%, sys=1.53%, ctx=192372, majf=0, minf=10
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued    : total=r=95741/w=96546/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: io=382964KB, aggrb=3191KB/s, minb=3191KB/s, maxb=3191KB/s, mint=120001msec, maxt=120001msec
  WRITE: io=386184KB, aggrb=3218KB/s, minb=3218KB/s, maxb=3218KB/s, mint=120001msec, maxt=120001msec

Disk stats (read/write):
  nvme0n1: ios=95665/97296, merge=0/23, ticks=60992/56404, in_queue=596, util=0.30%

```





```
[ec2-user@ip-10-0-2-224 ~]$ fio randomreadwrite.fio
job1: (g=0): rw=randrw, bs=64K-64K/64K-64K/64K-64K, ioengine=libaio, iodepth=64
...
fio-2.14
Starting 4 processes
Jobs: 4 (f=4): [m(4)] [100.0% done] [91776KB/98.90MB/0KB /s] [1434/1582/0 iops] [eta 00m:00s]
job1: (groupid=0, jobs=4): err= 0: pid=19442: Thu Sep 17 07:26:58 2020
  read : io=11539MB, bw=98457KB/s, iops=1538, runt=120011msec
    slat (usec): min=3, max=22242, avg=1300.27, stdev=2360.83
    clat (msec): min=5, max=145, avg=81.43, stdev=24.11
     lat (msec): min=5, max=152, avg=82.73, stdev=24.51
    clat percentiles (msec):
     |  1.00th=[   31],  5.00th=[   40], 10.00th=[   42], 20.00th=[   75],
     | 30.00th=[   80], 40.00th=[   81], 50.00th=[   83], 60.00th=[   84],
     | 70.00th=[   86], 80.00th=[   89], 90.00th=[  122], 95.00th=[  127],
     | 99.00th=[  133], 99.50th=[  137], 99.90th=[  141], 99.95th=[  143],
     | 99.99th=[  143]
  write: io=11560MB, bw=98639KB/s, iops=1541, runt=120011msec
    slat (usec): min=4, max=25342, avg=1291.70, stdev=2327.35
    clat (msec): min=6, max=149, avg=82.22, stdev=24.13
     lat (msec): min=6, max=162, avg=83.51, stdev=24.52
    clat percentiles (msec):
     |  1.00th=[   32],  5.00th=[   41], 10.00th=[   42], 20.00th=[   76],
     | 30.00th=[   80], 40.00th=[   83], 50.00th=[   84], 60.00th=[   85],
     | 70.00th=[   87], 80.00th=[   89], 90.00th=[  123], 95.00th=[  127],
     | 99.00th=[  135], 99.50th=[  139], 99.90th=[  141], 99.95th=[  143],
     | 99.99th=[  145]
    lat (msec) : 10=0.30%, 20=0.23%, 50=15.56%, 100=68.69%, 250=15.21%
  cpu          : usr=0.42%, sys=0.67%, ctx=126751, majf=0, minf=47
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=99.9%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued    : total=r=184623/w=184966/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: io=11539MB, aggrb=98456KB/s, minb=98456KB/s, maxb=98456KB/s, mint=120011msec, maxt=120011msec
  WRITE: io=11560MB, aggrb=98639KB/s, minb=98639KB/s, maxb=98639KB/s, mint=120011msec, maxt=120011msec

Disk stats (read/write):
  nvme0n1: ios=184516/185735, merge=0/28, ticks=2631028/2740840, in_queue=5253412, util=99.85%
```


```
[ec2-user@ip-10-0-2-127 ~]$ fio randomreadwrite.fio
job1: (g=0): rw=randrw, bs=64K-64K/64K-64K/64K-64K, ioengine=libaio, iodepth=64
...
fio-2.14
Starting 4 processes
Jobs: 4 (f=4): [m(4)] [100.0% done] [95680KB/97088KB/0KB /s] [1495/1517/0 iops] [eta 00m:00s]
job1: (groupid=0, jobs=4): err= 0: pid=25115: Thu Sep 17 07:26:51 2020
  read : io=11545MB, bw=98510KB/s, iops=1539, runt=120012msec
    slat (usec): min=3, max=17234, avg=1297.68, stdev=2674.65
    clat (msec): min=7, max=153, avg=81.32, stdev=29.70
     lat (msec): min=11, max=153, avg=82.62, stdev=30.19
    clat percentiles (msec):
     |  1.00th=[   22],  5.00th=[   39], 10.00th=[   41], 20.00th=[   43],
     | 30.00th=[   76], 40.00th=[   81], 50.00th=[   84], 60.00th=[   85],
     | 70.00th=[   87], 80.00th=[  116], 90.00th=[  126], 95.00th=[  128],
     | 99.00th=[  137], 99.50th=[  139], 99.90th=[  143], 99.95th=[  143],
     | 99.99th=[  145]
  write: io=11576MB, bw=98771KB/s, iops=1543, runt=120012msec
    slat (usec): min=4, max=14891, avg=1293.32, stdev=2669.37
    clat (msec): min=7, max=147, avg=82.17, stdev=29.79
     lat (msec): min=11, max=157, avg=83.46, stdev=30.26
    clat percentiles (msec):
     |  1.00th=[   29],  5.00th=[   40], 10.00th=[   42], 20.00th=[   43],
     | 30.00th=[   77], 40.00th=[   82], 50.00th=[   84], 60.00th=[   85],
     | 70.00th=[   88], 80.00th=[  118], 90.00th=[  127], 95.00th=[  130],
     | 99.00th=[  139], 99.50th=[  141], 99.90th=[  143], 99.95th=[  145],
     | 99.99th=[  145]
    lat (msec) : 10=0.01%, 20=0.89%, 50=23.59%, 100=51.93%, 250=23.59%
  cpu          : usr=0.33%, sys=0.52%, ctx=125913, majf=0, minf=43
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=99.9%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.1%, >=64=0.0%
     issued    : total=r=184724/w=185214/d=0, short=r=0/w=0/d=0, drop=r=0/w=0/d=0
     latency   : target=0, window=0, percentile=100.00%, depth=64

Run status group 0 (all jobs):
   READ: io=11545MB, aggrb=98509KB/s, minb=98509KB/s, maxb=98509KB/s, mint=120012msec, maxt=120012msec
  WRITE: io=11576MB, aggrb=98770KB/s, minb=98770KB/s, maxb=98770KB/s, mint=120012msec, maxt=120012msec

Disk stats (read/write):
  nvme0n1: ios=184602/186431, merge=0/31, ticks=3306872/3429952, in_queue=6620356, util=99.91%
```

**Pull request closed without merging**
