### PR TITLE
Docker 1.12.1

### PR DESCRIPTION
**Pull request by toolmantim**
Bump to [Docker 1.12.1](https://github.com/docker/docker/releases/tag/v1.12.1)

### CODE REVIEW

**Comment by toolmantim** [comment]
It appears there's no yum package for Docker 1.12.0 just yet

**Comment by toolmantim** [comment]
Still not available…

**Comment by bforchhammer** [comment]
The install-script on https://get.docker.com installs packages from `https://yum.dockerproject.org/`, which is probably up to date? Maybe we can borrow something from that script... or just run `curl -sSL https://get.docker.com/ | sh` of course, but then you won't be able to control the installed version, I think.

**Comment by toolmantim** [comment]
@bforchhammer that's a good idea. We could just start an instance, run that installer, copy out the yum repo config, and just use that!

**Comment by toolmantim** [comment]
Turns out that script just installs it from Amazon's yum repos. I managed to install it via the centos 6 yum repo package, but I'm not sure that is such a good idea…

```
cat >/etc/yum.repos.d/docker.repo <<-EOF
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/6
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF
yum install docker-engine
```

**Comment by ans0600** [comment]
Could we also upgrade to overlay2 here: https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/conf/docker/docker.conf#L7

**Comment by toolmantim** [comment]
I've just changed to performing a manual install of Docker, and switched to overlay2 whilst we were there. The stack json URL is https://s3.amazonaws.com/buildkite-aws-stack/docker-1-12-0/aws-stack.json if you wanted to test  — I'm going to test this on our own CI instances for a day before merging

**Comment by toolmantim** [comment]
It's looking mostly stable, although I did get one `ssh: connect to host github.com port 22: Connection timed out` error out of 1100ish job runs so far. I'm not sure if this is Docker networking weirdness, or just a regular old GitHub/network timeout.

**Comment by bforchhammer** [comment]
Sounds promising :-)

**Comment by toolmantim** [comment]
Ok, this looks stable. 🚀 town

**Comment by bforchhammer** [comment]
I've just updated our stacks as well... looks good so far ;-)

**Pull request merged**
