### PR TITLE
Add Name tags to more AWS resources

### PR DESCRIPTION
**Pull request by SomeoneWeird**

### CODE REVIEW

**Comment by toolmantim** [comment]
Nice! Should we do the same with the EC2 instances?

**Comment by SomeoneWeird** [comment]
Currently the EC2 instances [get tagged statically with `buildkite-agent`](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/buildkite-elastic.yml#L443-L444), it would be cool to maybe prepend the stack name so you can differentiate them if you have multiple stacks?

[](url)

**Comment by toolmantim** [comment]
Yes! If we could add the stack name that'd be ace. Potentially even before `buildkite-agent`?

**Comment by lox** [comment]
I'm going to merge this as-is. We can talk more tags later.

**Comment by SomeoneWeird** [comment]
Oops! I totally forgot about this, sorry folk!

**Pull request merged**
