### PR TITLE
Add a boolean to override replacing the asg

### PR DESCRIPTION
**Pull request by nitrocode**
Should solve this https://github.com/buildkite/elastic-ci-stack-for-aws/issues/764

Please review when time permits

@yob @chloeruka @lox

### CODE REVIEW

**Review by chloeruka — APPROVED** [review]
This change looks sensible and low-impact to me, and will help folks get this optimisation if they want it while we test out if we want this to become the new default. @yob @lox can you comment on whether this is alright as far as our design philosophy/parameter naming goes?

**Comment by jamesholmes-linktree** [comment]
Please don't make this the new default.

**Comment by nitrocode** [comment]
You mean don't make `WillReplace: true` the new default?

**Comment by jamesholmes-linktree** [comment]
For clarity, please leave the current behaviour of WillReplace=true as the default.

**Comment by nitrocode** [comment]
Ah yes the default in this pr is the same as the current behavior in the stack

**Comment by nitrocode** [comment]
@jamesholmes-linktree @chloeruka any update on the discussion of this pr?

**Comment by keithduncan** [comment]
I’m going to close this as https://github.com/buildkite/elastic-ci-stack-for-aws/pull/781 has merged, @nitrocode please let us know if this is still an issue and we can look into it further with you 🙇‍♂️

**Comment by freewil** [comment]
I think this issue should be revisited. I'm working on a project to regularly build custom AMIs multiple times throughout the day. I'm currently working with v5.5.1 (nothing seems to have changed relative to this more recently) and when updating the stack with an updated `ImageId` or just updating the stack with no changes to re-resolve the AMI value via SSM with `ImageIdParameter`, the ASG is re-created causing in-progress builds to be killed. This is very disruptive for my company to do at any given 24 hour period, especially at peak working hours.

When I set `WillReplace: false`, as in this PR, it fixes the issue - the LaunchTemplate is updated, the ASG is not re-created, and any existing EC2 instances continue running, but any new instances launch with the newly-updated AMI.

I'm not sure if this PR is the correct solution, but you really should be able to at least update the AMI via `ImageId` or `ImageIdParameter` without killing existing instances as described in the `image-builder` README: https://github.com/buildkite/image-builder#applying-built-images-to-elastic-stack

**Comment by nitrocode** [comment]
@freewil if you read the linked issue, it sounds like they don't want to create new input variables and they like how the asg is recreated so your best bet is to fork this repo and use your own release. 🤷‍♂️

**Pull request closed without merging**
