### PR TITLE
Create a parameter to determine whether public IPs are assigned to instances

### PR DESCRIPTION
**Pull request by holmesjr**

### CODE REVIEW

**Comment by lox** [comment]
I suspect that if you don't associate public IP's then they won't be able to access the external internet without a NAT Gateway.

**Comment by holmesjr** [comment]
Yep, that's the intent. For security, we delpoy our agents exactly that way. I should have mentioned that this fixes #117.

**Comment by lox** [comment]
Interesting, how does the agent contact buildkite.com without access to the internet?

**Comment by holmesjr** [comment]
We have a NAT gateway in our public subnet. Since the VPC provisioned in this template doesn't, perhaps a note in the readme that the option is only suitable when we have existing VPC resources is appropriate. I can add that to the PR if you like.

**Comment by lox** [comment]
Ah right, that makes sense. I was going to basically introduce this underlying VPC structure:

https://github.com/lox/cloudformation-templates/blob/master/vpc.yml

**Comment by holmesjr** [comment]
Awesone, I'm all for a default structure that enforces better security. There's little reason to run instances in a public subnet.

**Comment by lox** [comment]
Could we just defer the associating of public ip's to the VPC/Subnet? That way a config like yours would work as expected.

**Comment by holmesjr** [comment]
That would be a reasonable change, as long as people know that it's up to their subnet to dictate the behaviour. In that case, just removing the attribute from the launch config should be enough.

**Comment by lox** [comment]
I wonder how CloudFormation copes with updating underlying VPC pieces.

**Comment by holmesjr** [comment]
A change to subnet behaviour would require no interruption: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html#cfn-ec2-subnet-mappubliciponlaunch

**Comment by lox** [comment]
My concern with merging this is that if people select "false" for this and don't provide their own vpc/subnets, they will have non-functioning agents. I think we need to get a NAT Gateway into the default VPC before we could do this.

**Comment by holmesjr** [comment]
Agreed, it's a better pattern and a good example of how people can set up secure VPCs.

**Comment by lox** [comment]
Have decided to merge this in, the other PR will take some more thought. Thanks for the contribution @holmesjr.

**Comment by jsierles** [comment]
Did the other PR for adding a NAT Gateway ever surface? If not, is the best option here to setup a VPC with a NAT gateway and assign it to the stack?

**Pull request merged**
