### PR TITLE
Add support for billing tags

### PR DESCRIPTION
**Pull request by tduffield**
Adds two new configuration values (`BuildkiteBillingTagName` and `BuildkiteBillingTagValue`) that can be used to apply a Cost Allocation Tag to instances created by the ASG.

### CODE REVIEW

**Comment by lox** [comment]
I wonder if these need to be configurable, vs just adding the `aws:createdBy` with something to indicate elastic stack.

Ideally we'd like to keep parameters to a minimum, as they make it harder for people to understand what needs configuring. 

If you wanted arbitrary tags, presumably you could just use the Additional Tags section when you are creating the cloudformation stack?

**Comment by tduffield** [comment]
They need to be configurable because people may use a different tag other than `aws:createdBy` to manage cost centers. For example, my team uses `X-Application`. 

As for the Additional Tags section, those are buildkite tags and we need very specific AWS tags to use in Cost Center.

**Comment by tduffield** [comment]
@lox have you had an opportunity to think on this any more?

**Comment by lox** [comment]
Yup, let's merge it in. Thanks for this and thanks for your patience, have been at AWS Summit.

**Comment by lox** [comment]
Hmmmm. The build is failing with `Your account is not allowed to create tag aws:createdBy`

**Comment by tduffield** [comment]
@lox where do I specify additional AWS tags?

**Pull request merged**
