### PR TITLE
Create the secrets bucket if left blank

### PR DESCRIPTION
**Pull request by lox**
This creates a secrets bucket if none is provided. This bucket will be left in place when the stack is deleted.

### CODE REVIEW

**Comment by lox** [comment]
I'm not 100% sure this is useful. Thoughts @toolmantim?

**Comment by toolmantim** [comment]
I think it is! I think the "Getting Started" guide will be improved, because it's just "Add a key to this bucket and run your GitHub project's build" instead of "Create a bucket, edit the stack, etc etc"

**Comment by lox** [comment]
With the caveat that you need to explain how to figure out the bucket name

**Comment by toolmantim** [comment]
Yeah… it's still better I think. "Find your stack’s secrets bucket, add your key, run a build" vs "Create a secrets bucket, add the key, edit your stack, update your agents, run a build"

**Comment by lox** [comment]
Yup, true.

**Comment by lox** [comment]
Would it be going to far to have a policy on the bucket that prevented non-encrypted contents?

```
{
   "Version":"2012-10-17",
   "Id":"PutObjPolicy",
   "Statement":[{
         "Sid":"DenyUnEncryptedObjectUploads",
         "Effect":"Deny",
         "Principal":"*",
         "Action":"s3:PutObject",
         "Resource":"arn:aws:s3:::YourBucket/*",
         "Condition":{
            "StringNotEquals":{
               "s3:x-amz-server-side-encryption":"aws:kms"
            }
         }
      }
   ]
}
```

**Comment by toolmantim** [comment]
Oh, if it's not standard I think that'd be a very nice option!

If it is standard, can you upload it as encrypted via the AWS web console? Or `cli` only?

**Comment by lox** [comment]
Thoughts on getting this in as 2.1.0 @toolmantim? It should be non-breaking.

**Pull request merged**
