### PR TITLE
Use an SSM Parameter for BuildkiteAgentToken

### PR DESCRIPTION
**Pull request by lox**
Another take on https://github.com/buildkite/elastic-ci-stack-for-aws/pull/576

Feels @lucas044?

### CODE REVIEW

**Comment by holmesjr** [comment]
I know you've had this discussion, but can you consider using secrets manager?

I ask because a reference to SSM in this way uses a plain-text string. Resolving a secrets manager value allows for KMS:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-secretsmanager

**Comment by lox** [comment]
By the same token, we could use ssm secure if we used Dynamic References @holmesjr.

I lean more towards this approach as it's backwards compatible and the UX is slightly easier for first-time users, but it would be nice to have a way to use encrypted storage.

**Comment by lox** [comment]
Perhaps the approach in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/576 was better after all. 😬

**Comment by lucas044** [comment]
I have no real opinion about either option at this point.
Weighted to SM over SSM but I'm more weighted towards not having my secret exposed on the lambda environment variable more :joy:

**Comment by lox** [comment]
I am back to being paralysed by indecision 😅

**Comment by lox** [comment]
Yeah, going back to #576, at least that way we have options.

**Comment by lox** [comment]
Re-considering.

**Comment by holmesjr** [comment]
> By the same token, we could use ssm secure if we used Dynamic References @holmesjr.
> 

The docs point out the difference:

> The secretsmanager dynamic reference can be used in all resource properties. Using the secretsmanager dynamic reference guarantees that neither Secrets Manager nor CloudFormation logs or persists any resolved secret value.

vs

> Currently, secure string parameters can only be used for resource properties that support the ssm-secure dynamic reference pattern. (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#template-parameters-dynamic-patterns-resources)

**Comment by lox** [comment]
Gotcha @holmesjr. There doesn't seem to be any way of dynamically creating those dynamic references though, for instance from a path in a parameter template.

**Comment by lox** [comment]
I think it's just too much of a bummer that SecureString isn't supported.

**Pull request closed without merging**
