### PR TITLE
Ensure powershell scripts fail when executable fails

### PR DESCRIPTION
**Pull request by jeremiahsnapp**
We have to explicitly test the exit status after running executables because powershell doesn't automatically fail when an executable's exit status is non-zero.

We've deployed these changes to our own Windows Buildkite packer template and it really increases the confidence that the powershell scripts haven't silently failed.

### CODE REVIEW

**Comment by lox** [comment]
Ugh, so gross 😢

Are you sure there isn't an alternative?

**Comment by tduffield** [comment]
Other than not use Powershell? Not that we've found. We got this guidance from a "Windows expert" (for whatever that's worth). But, for context, think of Powershell as a programming language, not a scripting one. You gotta tell Go when to exit, and with what error code.

**Comment by tduffield** [comment]
At least here we don't have to handle `nil` :trollface:

**Comment by lox** [comment]
Cool, let's merge this in. Is what it is!

**Pull request merged**
