### PR TITLE
Optionally mount Instance Storage on boot

### LINKED ISSUE #464: Instance Storage Support
I think we'd see a sizeable performance boost on IO-heavy builds if using Instance Storage was supported so we can use the NVME SSD instances (`c5d`, `m5d`).

### PR DESCRIPTION
**Pull request by lox**
Since lots of instances seem to have fancy fast instance storage now, this mounts whatever is available at `/ephemeral` and uses that for docker storage.  

Closes #464.

### CODE REVIEW

**Comment by benesch** [comment]
This would be a huge help to us! Anything I can do to help move this along?

(By the way, I think we'd also want the option to move /var/lib/buildkite to the local storage, so that compilation would also see the faster I/O.)

**Comment by lox** [comment]
@benesch would be very interested to see if you actually saw performance improvements that were meaningful from this change. I guess there is only one way to find out!

**Comment by ans0600** [comment]
Hi @lox, I am keen to try this PR. Anything I can do to help move this along?

**Comment by ans0600** [comment]
Hi @lox, I tried this commit and the instance failed to start docker daemon with following error. The docker daemon.json file seems to be empty.

```
[root@ip-172-31-1-61 ec2-user]# tail -f /var/log/docker
Aug 10 02:41:10 ip-172-31-15-205 dockerd: unable to configure the Docker daemon with file /etc/docker/daemon.json: EOF

[root@ip-172-31-1-61 ec2-user]# ls /etc/docker/daemon.json
/etc/docker/daemon.json
[root@ip-172-31-1-61 ec2-user]# cat /etc/docker/daemon.json

``` 

I tried this branch with following steps:

- Checkout this branch is run make
- In packer folder, run packer build. I can see an AMI is created in my account
- Use the "aws-stack.yml" in build directory to launch the cloudformation stack. I specified the AMI ID with the one generated in previous step.

After launch, I can see the ephemeral drives are created 👍 . The instance type is m5d.24large
```
[root@ip-172-31-1-61 ec2-user]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        185G     0  185G   0% /dev
tmpfs           185G     0  185G   0% /dev/shm
tmpfs           185G  788K  185G   1% /run
tmpfs           185G     0  185G   0% /sys/fs/cgroup
/dev/nvme0n1p1   10G  1.8G  8.3G  18% /
/dev/nvme1n1    838G  888M  837G   1% /ephemeral
tmpfs            37G     0   37G   0% /run/user/1000
```

**Comment by lox** [comment]
@ans0600 really appreciate the testing! I'll get this rebased and see if I can figure out what is going on.

**Comment by ans0600** [comment]
@lox Just want to check if the PR is ready to test again?

**Comment by lox** [comment]
@jradtilbrook or @ans0600 if either of you get a chance to test this out, let me know!

**Comment by lox** [comment]
For those following along, you can test it out with https://s3.amazonaws.com/buildkite-aws-stack/add-instance-storage/aws-stack.yml. Would love feedback!

**Comment by jradtilbrook** [comment]
I'm under the pump for other things at work so I don't think I'll be able to try this out any time soon sorry - just in case you were relying/waiting on me

**Comment by lox** [comment]
No worries @jradtilbrook, some other folks asked about it!

**Comment by dgarbus** [comment]
I just gave this a try and confirmed that it is still failing to spin up new instances. The issue appears to be that the jq filter syntax being used does not support key names containing hyphens (alphanumeric characters and underscores only): https://github.com/buildkite/elastic-ci-stack-for-aws/pull/557/files#diff-75f0630f614eebc548f6a4beeda4f879R23

To fix it, we just need to add double quotes around the key name:
```
--- a/packer/conf/bin/bk-configure-docker.sh
+++ b/packer/conf/bin/bk-configure-docker.sh
@@ -20,5 +20,5 @@ fi

 # Move docker root to the ephemeral device
 if [[ "${BUILDKITE_ENABLE_INSTANCE_STORAGE:-false}" == "true" ]] ; then
-  cat <<< "$(jq '.data-root="/ephemeral/docker"' /etc/docker/daemon.json)" > /etc/docker/daemon.json
+  cat <<< "$(jq '."data-root"="/ephemeral/docker"' /etc/docker/daemon.json)" > /etc/docker/daemon.json
 fi
```
In fact, it looks like we do exactly that for the "userns-remap" feature in that same script.

I applied the patch above, built an AMI, and confirmed that the instance stays running. However, when running a build, I ran into the next error:
```
Checking docker
--
  | CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
  | Checking disk space
  | df: ‘/var/lib/docker/’: No such file or directory
  | Cleaning up docker resources older than 4h
  | Total reclaimed space: 0B
  | Checking disk space again
  | df: ‘/var/lib/docker/’: No such file or directory
  | Disk health checks failed
  | 🚨 Error: Error setting up bootstrap: The global environment hook exited with status 1
  |  
```
Which I fixed by changing this:
```
--- a/packer/conf/bin/bk-check-disk-space.sh
+++ b/packer/conf/bin/bk-check-disk-space.sh
@@ -4,7 +4,7 @@ set -euo pipefail
 DISK_MIN_AVAILABLE=${DISK_MIN_AVAILABLE:-5242880} # 5GB
 DISK_MIN_INODES=${DISK_MIN_INODES:-250000} # docker needs lots

-DOCKER_DIR="/var/lib/docker/"
+DOCKER_DIR="$(jq -r '."data-root" // "/var/lib/docker"' /etc/docker/daemon.json)"

 disk_avail=$(df -k --output=avail "$DOCKER_DIR" | tail -n1)
```
Now everything appears to be working.

**Comment by ouranos** [comment]
Hi @lox, 
I've tested this last week.

I've:
- rebased this branch onto the latest `master` branch
- applied @dgarbus patches

I've replaced our "builder" stack (mostly docker/yarn/webpack) by this new stack keeping most of the parameters the same and just changing the instance type: `m5.4xlarge` with 500 GiB EBS (1500 IOPS)
-> `m5d.4xlarge`

With a cold docker cache, the build went from ~60min down to ~16min. So this is a massive improvement for us!

I had to apply the following patch to fix the striped volume creation and mount:
```diff
--- a/packer/linux/conf/bin/bk-mount-instance-storage.sh
+++ b/packer/linux/conf/bin/bk-mount-instance-storage.sh
@@ -10,16 +10,13 @@ if [[ "${BUILDKITE_ENABLE_INSTANCE_STORAGE:-false}" != "true" ]] ; then
   exit 0
 fi

+# Install nvme-cli to list NVMe SSD instance store volumes
+yum -y -d0 install nvme-cli
+
 devicemount=/ephemeral
 logicalname=/dev/md0
-candidates=( '/dev/nvme1n1' )
-devices=()
+devices=($(nvme list | grep "Amazon EC2 NVMe Instance Storage"| cut -f1 -d' '))

-for candidate in "${candidates[@]}" ; do
-  if [[ -b $candidate ]] ; then
-    devices+=("$candidate")
-  fi
-done

 if [[ "${#devices[@]}" -gt 0 ]] ; then
   mkdir -p "$devicemount"
@@ -35,13 +32,13 @@ if [[ "${#devices[@]}" -eq 1 ]] ; then
   fi

 elif [[ "${#devices[@]}" -gt 1 ]] ; then
-  yes | mdadm \
+  mdadm \
     --create "$logicalname" \
     --level=0 \
     -c256 \
     --raid-devices="${#devices[@]}" "${devices[@]}"

-  echo \'DEVICE "${devices[*]}"\' > /etc/mdadm.conf
+  echo "DEVICE ${devices[*]}" > /etc/mdadm.conf

   mdadm --detail --scan >> /etc/mdadm.conf
   blockdev --setra 65536 "$logicalname"
```

**Comment by ouranos** [comment]
I also have a branch based off `stable-4-4` on our fork if that helps: 
https://github.com/buildkite/elastic-ci-stack-for-aws/compare/stable-4-4...range-me:add-instance-storage-stable

**Comment by nitrocode** [comment]
Great addition! i believe this will help us as well. What's the status of this pr?

Is the only change left incorporating @ouranos changes into this pr?

Or would it be better to use the branch with @ouranos additional commits in a separate pr?

**Comment by woodhull** [comment]
We've also tried this out. It made a modest improvement to docker image build times in our situation. Would still be good to see this merged so that it can be experimented with by consumers without forking the stack.

**Comment by ouranos** [comment]
@yob @lox Any updates on this?
It's working great for us but we have to maintain a branch and keep it up to date with upstream (and build new AMIs). 
It would be great to get it merged (any branch would work for us, eg: `5-0-stable` or `master`)

I'd be happy to rebase/update our branch and open a new PR if that helps.

**Comment by nijave** [comment]
We're using something similar for node since the massive quantity of files really drags down the default config. We've seen NVMe instances with soft RAID0 hit over 70k IOPs so there's definitely a boost here. If I remember/have some time I'll post what we have (we've been using it over a year now)

I think our main difference is mounting NVMe to /media/ephemeral then bind mounting:
```
/media/ephemeral/docker -> /var/lib/docker
/media/ephemeral/buildkite -> /var/lib/buildkite
```

**Comment by ouranos** [comment]
> @yob @lox Any updates on this?
> It's working great for us but we have to maintain a branch and keep it up to date with upstream (and build new AMIs).
> It would be great to get it merged (any branch would work for us, eg: `5-0-stable` or `master`)
> 
> I'd be happy to rebase/update our branch and open a new PR if that helps.

@sj26 @pda Pinging you since I saw you were looking at #790 which fall into the same category.

Let me know what you think of this and if I can help in getting it merged 🙏

**Comment by ryansdwilson** [comment]
Curious if anyone has any advice for a buildkite noob on how to implement this. We're on the beta version of the stack ami.. we could move to edge. We have 3gb docker files that are super slow to pull because of an IO rate limit. Some have discussed using tmpfs/ram ... seems like this would be a common issue. Hoping you can steer us in the right way. Thank you all for all your hard work making buildkite better!

**Comment by ryansdwilson** [comment]
I'd like to bump the request to get this on master. We're hand crafting this right now and would love to see it on beta or edge.

**Comment by yob** [comment]
Hi all,

We'd also love to see this in an official release, but in the short term we're pretty flat out. If anyone running a fork with this feature is keen though, we'd love to help you land it in master (/cc @ouranos). A new PR is probably best, either based on this one or something totally fresh.

We haven't fully talked about design goals internally, and y'all who are using instance storage might have a better understanding of what's possible anyway. I think we'd be keen to see this as a new opt-in stack parameter, even for instance types that come with instance storage.

It'd great if the local storage could be used for both docker and the builds directory, so it's suitable for a variety of IO-heavy workloads.

One concern we have is how it might impact instance boot time, so it'd be great to see some basic measurements of how the new option impacts that. Longer boot time isn't necessarily a problem, but it might impact how stacks using this option decide to autoscale (if at all).

**Comment by ryansdwilson** [comment]
Hi @yob We're hoping to hire the guys at s&w to help us with our infrastructure. We're thinking that this IO speed issue may be one of our rate limiters so perhaps this is something we can pay for to help the community. Curious if you have thoughts on making it to support either instance store or ramdisk/tmpfs as has been previously mentioned. Most CI runs in our experience are not RAM bound and there tends to be tons of excess memory on our CI nodes...this approach avoids the extra boot time associated with waiting for a SSD backed instance. We'll talk to the S&W guys and see how they feel about this work potentially getting put into a PR. thanks for all your work at BK we love the product. 


> Hi all,
> 
> We'd also love to see this in an official release, but in the short term we're pretty flat out. If anyone running a fork with this feature is keen though, we'd love to help you land it in master (/cc @ouranos). A new PR is probably best, either based on this one or something totally fresh.
> 
> We haven't fully talked about design goals internally, and y'all who are using instance storage might have a better understanding of what's possible anyway. I think we'd be keen to see this as a new opt-in stack parameter, even for instance types that come with instance storage.
> 
> It'd great if the local storage could be used for both docker and the builds directory, so it's suitable for a variety of IO-heavy workloads.
> 
> One concern we have is how it might impact instance boot time, so it'd be great to see some basic measurements of how the new option impacts that. Longer boot time isn't necessarily a problem, but it might impact how stacks using this option decide to autoscale (if at all).

**Comment by yob** [comment]
Sounds interesting @ryansdwilson.

I haven't heard any internal discussions about the pros/cons of ramdisk. It sounds like an interesting option, and some data on the different boot times would be awesome.

I'm not very familiar with instance local storage. Do they take a long time to boot because AWS just take longer to provision them or is the the post-boot initialising of the disks that's the issue?

I can imagine the viability of ramdisks would vary a lot from customer to customer. I know some of our customers use a **lot** of storage space - often for docker images, large monorepos, or both.

**Comment by woodhull** [comment]
We are also still maintaining a fork just to be able to have this feature and would encourage Buildkite to find a way to prioritize supporting it.

Boot time is not a concern for us since our IO bound instance that builds the docker containers is persistent. The fleet of ephemeral machines that runs tests as part of the  build only have EBS disks, and are not IO bound.

**Comment by nijave** [comment]
> Sounds interesting @ryansdwilson.
> 
> I haven't heard any internal discussions about the pros/cons of ramdisk. It sounds like an interesting option, and some data on the different boot times would be awesome.
> 
> I'm not very familiar with instance local storage. Do they take a long time to boot because AWS just take longer to provision them or is the the post-boot initialising of the disks that's the issue?
> 
> I can imagine the viability of ramdisks would vary a lot from customer to customer. I know some of our customers use a **lot** of storage space - often for docker images, large monorepos, or both.

I haven't done a ton of measurements, but the script we were using that sets up mdraid w/ xfs only took a few seconds to run. I remember we've seen some issues acquiring `d` instances due to availability although I think it's gotten better and using all available AZs help (many times they're unavailable in a single AZ, temporarily). 

(might not be the most... ergonomic... of shelf scripts, but it seems to work reliably for the last 1+ yr)
```
#!/bin/sh

echo "kernel.keys.maxkeys = 10000" | sudo tee /etc/sysctl.d/98-maxkeys.conf
sudo sysctl -f --system

sudo systemctl stop docker
sudo rm -rf /var/lib/docker/*
sudo chmod 400 /var/lib/docker

sudo mdadm --create --verbose /dev/md0 --level=0 --raid-devices=2 /dev/nvme1n1 /dev/nvme2n1
sudo mkfs.xfs /dev/md0

sudo mkdir -p /media/ssd
sudo chmod 400 /media/ssd

echo /dev/md0 /media/ssd xfs defaults,noatime 0 0 | sudo tee -a /etc/fstab
sudo mount -a

sudo mkdir -p /media/ssd/var/lib/docker
sudo mkdir -p /media/ssd/var/lib/buildkite-agent
sudo mkdir -p /var/lib/buildkite-agent
sudo rsync -aP /var/lib/buildkite-agent /media/ssd/var/lib/

echo /media/ssd/var/lib/docker /var/lib/docker none defaults,bind 0 0 | sudo tee -a /etc/fstab
echo /media/ssd/var/lib/buildkite-agent /var/lib/buildkite-agent none defaults,bind 0 0 | sudo tee -a /etc/fstab
sudo mount -a

sudo systemctl start docker
```

With whatever instances come with 2x300GB we were seeing machines hit around 72k IOPs as reported by iostat during builds so there is a pretty significant performance difference. We were seeing issues with rather large Docker containers during pull/extract (100k of files) and tearing down containers (afaik the filesystem does lots of syncs as it tears down each layer of the overlayfs). Almost all our stuff runs using the docker-compose plugin (there's a small pool of container builders that push to ECR then each "regular" instance pulls the image back down and runs tests, tools, etc inside them)

**Comment by ouranos** [comment]
Hi all,
Great to see some activity on this! I'm quite busy on my side but I'll try to find the time to prepare a new PR based on our fork.
We've been running it without any issues for almost a year now. We have a stack parameter to activate this feature (it's disabled by default).

I haven't benchmarked the slower boot time but it's not an issue for us as we have two stacks:
1. One builder stack for docker and webpack builds which is using big instances with nvme local storage which are rarely stopped (as per https://github.com/buildkite/elastic-ci-stack-for-aws#optimizing-for-slow-docker-builds). It's warmed up every morning with a scheduled build from `master`.
2. One test stack that pulls the docker images built by the builder stack and run all the tests. This stack doesn't use local storage and scale up/down normally.

**Comment by ouranos** [comment]
Hi all,

Just saw some activity on this today and I realised I never prepared the PR I offered in my last message.

I spent some time last week updating another of our stack to nvme storage and that went quite well. 

@keithduncan let me know if you need any help on this. I have a bit more time to spend on buildkite, so I'm happy to create a PR from our fork as I offered last time (and didn't do 😅 )

**Comment by keithduncan** [comment]
Hi @ouranos, I think I’ve incorporated all the patches mentioned here and am testing this on Linux now. If you spot anything missing from this implementation compared to yours let me know and I can look at incorporating it 😄 

One area I haven’t looked into yet is adding this to our Windows AMI, and is something I’m interested in adding. Pointers in this area would be appreciated!

**Comment by keithduncan** [comment]
it's happening gif

**Comment by ouranos** [comment]
Great work @keithduncan! 🙌 

> Hi @ouranos, I think I’ve incorporated all the patches mentioned here and am testing this on Linux now. If you spot anything missing from this implementation compared to yours let me know and I can look at incorporating it 😄

I've compared my branch with what is now in `master` and it looks good. The only other changes we have are unrelated (installing CloudWatch agent for memory monitoring, installing `buildx`, ...)

I have an isolated stack & set of pipelines for testing so I'll test the new stack and report. The branch I'm using is branched off `v5.1.0` so that'll also be a good opportunity to update to `v5.6.0`.

> One area I haven’t looked into yet is adding this to our Windows AMI, and is something I’m interested in adding. Pointers in this area would be appreciated!

Unfortunately, we're only using Linux AMI so I won't be able to help much with this.

**Pull request merged**
