### PR TITLE
Support encrypted EBS root volumes (take 2)

### LINKED ISSUE #318: Support encrypted EBS volumes
It would be a neat security boost if the stack had an option to enable [EBS encryption](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html).

This would need to be optional, as it limits the instance types you can use with the volumes.

### PR DESCRIPTION
**Pull request by lox**
Accidentally messed this up in #517, trying again. 

Closes #318.

### CODE REVIEW

**Comment by lox** [comment]
I think perhaps we might need to provide a set of encrypted AMIs if we want this to work. I don't know how keen I am to do that.

**Comment by lox** [comment]
> The process of creating an encrypted EBS boot volume begins with an existing AMI (either Linux or Windows). If you own the AMI, or if it is both public and free you can use it directly. Otherwise, you will need to launch the AMI, create an image from it, and then use that image to create the encrypted EBS boot volume (this applies, for example, to Windows AMIs). The resulting encrypted AMI will be private; you cannot share it with another AWS account.

Ah, right. Nope, we can't even provide them, they are per-account. For this to work, folks would need to copy the latest AMI into their account and encrypt it.

**Comment by mefellows** [comment]
My thinking for this feature is that it's targeted for those customers who would likely harden their own AMIs for compliance/security reasons - either based off a public AMI or re-created from your [template](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/packer/buildkite-ami.json). 

Does this sound reasonable or do you see obvious alternatives that we should pursue instead?

**Comment by ineffyble** [comment]
@lox If my understanding is correct, in that circumstance the user just copies & encrypts the AMI, and provides it as the existing `ImageID`.

The encrypted flag does not need to be set, because the AMI/snapshot is encrypted, so the volume is too.

So it might just be a case of mentioning that in the docs, with no code change neccessary.

**Comment by mefellows** [comment]
Thanks, this all actually makes a lot of sense, and we'll give it a go in the couple of days. Appreciate your responsiveness 👍

**Comment by lox** [comment]
No problems!

**Pull request closed without merging**
