### PR TITLE
Upgrade packer

### LINKED ISSUE #704: Upgrade Packer from 1.0.4 (August 2017) to latest version
Packer is now 1.6.2 (August 2020) and this is currently using 1.0.4 (August 2017). Lots of bugs and additional features have been added since.

https://github.com/hashicorp/packer/blob/master/CHANGELOG.md

### PR DESCRIPTION
**Pull request by sj26**
Let's see how far we can bump packer before it breaks.

Fixes #704.

### CODE REVIEW

**Comment by yob** [comment]
I'm not fully across the elastic stack CI yet, how does it use packer?

I notice the [first build on this branch](https://buildkite.com/buildkite-aws-stack/buildkite-aws-stack/builds/2041#b3dc7ea2-180d-46f7-a4db-ccb982a914f8) seems to have downloaded a packer docker image and then pushed a built EC2 image to s3 (at `s3://buildkite-aws-stack-test`).

I could be reading it wrong, but are [subsequent builds](https://buildkite.com/buildkite-aws-stack/buildkite-aws-stack/builds/2043#e9e86dab-da47-401d-9f92-6caf0acdea24) downloading the cached image from S3?

**Comment by sj26** [comment]
Packer builds the AMIs used by the auto-scaling groups.

But you're totally right, I didn't realise the images were being cached. I'll add a cache buster.

**Comment by sj26** [comment]
This is somewhat discouraging:

```
==> Builds finished but no artifacts were created.
  | panic: runtime error: invalid memory address or nil pointer dereference
  | 2020/09/07 05:03:47 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xd37c8f]
  | 2020/09/07 05:03:47 packer:
  | 2020/09/07 05:03:47 packer: goroutine 40 [running]:
  | 2020/09/07 05:03:47 packer: github.com/hashicorp/packer/builder/amazon/common.(*StepRunSpotInstance).Run(0xc0002ae540, 0x2819dc0, 0xc00073a740, 0x2817bc0, 0xc000739ad0, 0x0)
  | 2020/09/07 05:03:47 packer: 	/Users/mmarsh/go/src/github.com/hashicorp/packer/builder/amazon/common/step_run_spot_instance.go:186 +0xa4f
  | 2020/09/07 05:03:47 packer: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc00073a700, 0x2817bc0, 0xc000739ad0)
  | 2020/09/07 05:03:47 packer: 	/Users/mmarsh/go/src/github.com/hashicorp/packer/helper/multistep/basic_runner.go:72 +0x222
  | 2020/09/07 05:03:47 packer: github.com/hashicorp/packer/builder/amazon/ebs.(*Builder).Run(0xc00042a000, 0x281f640, 0xc0005f2fe0, 0x280d180, 0xc0002e8e20, 0x281a180, 0xc00000c658, 0x4bca9c, 0x1e1b880, 0x1e1b880, ...)
  | 2020/09/07 05:03:47 packer: 	/Users/mmarsh/go/src/github.com/hashicorp/packer/builder/amazon/ebs/builder.go:260 +0x1410
  | 2020/09/07 05:03:47 packer: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc000147300, 0x1, 0xc0006b54a0, 0x0, 0x0)
  | 2020/09/07 05:03:47 packer: 	/Users/mmarsh/go/src/github.com/hashicorp/packer/packer/rpc/builder.go:94 +0x1cd
  | 2020/09/07 05:03:47 packer: reflect.Value.call(0xc00007d080, 0xc00000c5b0, 0x13, 0x2544246, 0x4, 0xc0000a7f18, 0x3, 0x3, 0xc00073a3c0, 0xc0006b6988, ...)
  | 2020/09/07 05:03:47 packer: 	/usr/local/go/src/reflect/value.go:447 +0x449
  | 2020/09/07 05:03:47 packer: reflect.Value.Call(0xc00007d080, 0xc00000c5b0, 0x13, 0xc0006da718, 0x3, 0x3, 0x1, 0x72c03e, 0xc000598301)
  | 2020/09/07 05:03:47 packer: 	/usr/local/go/src/reflect/value.go:308 +0xa4
  | 2020/09/07 05:03:47 packer: net/rpc.(*service).call(0xc000079f40, 0xc0000907d0, 0xc000043458, 0xc000043460, 0xc0000f0880, 0xc000574260, 0x1e8b7e0, 0xc0006b547c, 0x18a, 0x1e1b880, ...)
  | 2020/09/07 05:03:47 packer: 	/usr/local/go/src/net/rpc/server.go:384 +0x14e
  | 2020/09/07 05:03:47 packer: created by net/rpc.(*Server).ServeCodec
  | 2020/09/07 05:03:47 packer: 	/usr/local/go/src/net/rpc/server.go:481 +0x47e
  | 2020/09/07 05:03:47 [INFO] (telemetry) ending amazon-ebs
  | 2020/09/07 05:03:47 ui error: Build 'amazon-ebs' errored: unexpected EOF
  | 2020/09/07 05:03:47 Builds completed. Waiting on interrupt barrier...
  | 2020/09/07 05:03:47 machine readable: error-count []string{"1"}
  | 2020/09/07 05:03:47 ui error:
  | ==> Some builds didn't complete successfully and had errors:
  | 2020/09/07 05:03:47 machine readable: amazon-ebs,error []string{"unexpected EOF"}
  | 2020/09/07 05:03:47 ui error: --> amazon-ebs: unexpected EOF
  | 2020/09/07 05:03:47 ui:
  | ==> Builds finished but no artifacts were created.
  | 2020/09/07 05:03:47 [INFO] (telemetry) Finalizing.
  | 2020/09/07 05:03:47 /bin/packer: plugin process exited
  | 2020/09/07 05:03:47 waiting for all plugin processes to complete...
  | 2020/09/07 05:03:47 /bin/packer: plugin process exited
  | 2020/09/07 05:03:47 /bin/packer: plugin process exited
  | 2020/09/07 05:03:47 /bin/packer: plugin process exited
  | 2020/09/07 05:03:47 /bin/packer: plugin process exited
  | 2020/09/07 05:03:47 /bin/packer: plugin process exited
  | 2020/09/07 05:03:47 /bin/packer: plugin process exited
  | 2020/09/07 05:03:47 /bin/packer: plugin process exited
  | 2020/09/07 05:03:47 /bin/packer: plugin process exited
  | 2020/09/07 05:03:47 /bin/packer: plugin process exited

```

**Comment by sj26** [comment]
This has been a very frustrating process, but I think these are all going to go green, and then this can ship.

**Comment by sj26** [comment]
It keeps getting stuck here during the windows build:
image

**Comment by sj26** [comment]
Still, all looks good — merging!

**Pull request merged**
