### PR TITLE
Support ebs encryption

### PR DESCRIPTION
**Pull request by lox**
Merged #334 in here so I can run CI against it. Thanks @ineffyble!

### CODE REVIEW

**Comment by lox** [comment]
Failing with this message @ineffyble:

https://lachlan.me/s/cqWQnzQMuOXMSo53ZNwSXohfHpiqw95mFh.png

**Comment by lox** [comment]
https://forums.aws.amazon.com/thread.jspa?threadID=156802 :(

**Comment by ineffyble** [comment]
Huh, that's sad :/

**Comment by lox** [comment]
It is sad. What we could do is mount a second volume for buildkite builds?

**Comment by lox** [comment]
I'm going to close this for now :(

**Pull request closed without merging**
