### PR TITLE
Change parameter help text

### PR DESCRIPTION
**Pull request by exidy**
Looking at the generated CloudFormation it seems the AvailabilityZones parameter is only used if creating subnets.

### CODE REVIEW

**Comment by toolmantim** [comment]
Thanks for the change. The new version might cause some people to think they need to fill it out for the basic case (no VpcId) if they didn't fill out Subnets. But this is only required if VpcId is set but Subnets is not, right?

**Comment by exidy** [comment]
No, if I'm understanding the stack correctly it's needed any time subnets are not specified. There's a fallback in there where it queries the region for the available AZs, but I think @lox had identified a failure case for that situation?

**Comment by toolmantim** [comment]
@lox any input?

**Comment by lox** [comment]
`AvailabilityZones` is entirely optional, and only needs to be used if you encounter the dreaded https://github.com/buildkite/elastic-ci-stack-for-aws/issues/41. 

I'd be inclined to phrase it "Optional - Comma-delimited list of VPC availability zones in which to create subnets. If not provided your account defaults are used, which are occasionally incorrect."

Is that too confusing?

**Comment by exidy** [comment]
It's hard to explain what's going on in the help text without making it war and peace! How about "Optional - defines which AZs subnets are created in if Subnets are not specified." That should steer someone in the right direction if they hit #41.

**Comment by lox** [comment]
Feel like making that change @exidy and we'll get this merged? :)

**Comment by exidy** [comment]
Updated with a slightly more grammatical version of the above.

**Pull request merged**
