### PR TITLE
Use ECS-Optimized AMI for base image

### PR DESCRIPTION
**Pull request by lox**
Docker considers Amazon Linux an "[unsupported distro](https://github.com/docker/docker/pull/23480)" and it seems like the relationship between the two is becoming increasingly strained. 

Currently we are using the [latest Amazon Linux AMI](https://aws.amazon.com/amazon-linux-ami/2016.09-release-notes/) and then installing Docker on it. An official Amazon package isn't available for 1.13, and tends to lag behind because kernel changes are often required in the underlying distro. 

This PR moves to the newer [ECS Optimized image](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html) from Amazon, which is basically a supported bundle of Amazon Linux, Docker 1.12.6 (currently) and ECS agent.

My hope is that this will be more stable.

### CODE REVIEW

**Comment by toolmantim** [comment]
I considered this long ago when I more closely followed the ECS project, and I think I even copy and pasted bits from their image into our stack at some point.

I'm not sure if this is worth it though. It's definitely a more battle-hardened setup, but unless we're moving the Elastic CI Stack to ECS why wouldn't we just switch to CoreOS?

**Comment by lox** [comment]
Yup, agreed @toolmantim. Beyond that, the ECS image seems to insist on devicemapper backend, which seems like a dead-end to me.

**Comment by lox** [comment]
After all the issues we've been seeing in #236 I've been really reconsidering this.

**Comment by toolmantim** [comment]
It could be worth experimenting with, especially if @piotrb has a repeatable environment for testing. I'm just not sure how many other bugs it might create in the process? Or if there's something we should be using instead of ECS? CoreOS maybe? I remember CoreOS Docker versions lagging behind a little bit?

**Comment by piotrb** [comment]
"repeatable environment for testing" .. eh .. I'd like that to be a semi stable CI cluster since its kinda our main one ;)

**Comment by toolmantim** [comment]
Sorry, I meant you seem to be able to reproduce the problem!

**Comment by lox** [comment]
Apologies @piotrb, we are working on a fix!

**Pull request closed without merging**
