### PR TITLE
Name tags for instances

### PR DESCRIPTION
**Pull request by exidy**
This PR adds "Name" tags for buildkite agents such that their purpose is clear in the AWS console. It also adds tags for the agent version and queue to assist with managing multiple agent stacks.

### CODE REVIEW

**Comment by lox** [comment]
Yup, probably makes sense. Another way to do this is to provide tags when creating the stack (http://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html)

**Comment by exidy** [comment]
Tagging the stack should tag the ASG - I wonder if the ASG will then propagate the tags to the instances?

**Comment by toolmantim** [comment]
It does! But from memory you have to remember to use Name and not name, and I also sometimes forget to do it. So there's some merit to making this easier… because you almost always want them just to be the same name as the stack yeah?

**Comment by exidy** [comment]
@toolmantim it's of particular significance for EC2 instances created via ASG via CloudFormation. Resources created directly get an autogenerated name which usually has the name of the stack in it already. As the EC2 instances aren't directly created by the stack, they don't benefit from this feature. Hence the explicit name tags.

**Comment by toolmantim** [comment]
Yep cool. I was meaning that I normally achieve this via the stack tags (if you add `Name` as the stack tag your ASGs instances will be named correctly). But this is more fool proof and obvious 👍

**Pull request merged**
