### PR TITLE
bump docker-compose version to 1.25.1

### PR DESCRIPTION
**Pull request by dreyks**
here we go again :D

### CODE REVIEW

**Comment by dalberto** [comment]
Anything that can be done to move this PR along?🙂 

docker-compose 1.24.x [introduces](https://docs.docker.com/compose/release-notes/#new-features-1) [buildkit](https://github.com/moby/buildkit) support which facilities dramatic build improvements. Locally, I've been able to reduce cold build times by over 60% and I'd love to bring those improvements to CI.

**Comment by lox** [comment]
What broke last time @dreyks?

**Comment by lox** [comment]
Let's give it a try!

**Comment by dreyks** [comment]
@lox it was https://github.com/docker/compose/pull/7052

**Pull request merged**
