### PR TITLE
Session manager plugin

### PR DESCRIPTION
**Pull request by nitrocode**
Closes https://github.com/buildkite/elastic-ci-stack-for-aws/issues/817

Not sure how to install the executable silently on Windows.

### CODE REVIEW

**Comment by yob** [comment]
I've run a build and confirmed this works as expected.

is it possible to rebase onto master (to get #819) and remove the merge commits?

**Comment by yob** [comment]
One thing I haven't done is actually test the plugin works. We don't really use SSM yet though, so that test wouldn't be straight forward. Have you been able to run a build with one of these AMIs and confirm the plugin works as intended?

**Comment by nitrocode** [comment]
> I've run a build and confirmed this works as expected.

Perfect.

> is it possible to rebase onto master (to get #819) and remove the merge commits?

Done.

> One thing I haven't done is actually test the plugin works. We don't really use SSM yet though, so that test wouldn't be straight forward. Have you been able to run a build with one of these AMIs and confirm the plugin works as intended?

I did not build an AMI but I did run the script on an x86 and an arm machine to make sure it installs correctly. Then I gave the iam role of my instance access to `ssm:StartSession` across `*` resources. Finally, I ran this command from the buildkite ec2 instance where I installed the `session-manager-plugin` and it worked as expected.

```bash
$ aws --region us-west-2 ssm start-session --target i-snip

Starting session with SessionId:
```

**Comment by yob** [comment]
Lovely, thanks!

**Pull request merged**
