### PR TITLE
Move CI scripts into conventional .buildkite dir

### PR DESCRIPTION
**Pull request by sj26**
Thoughts?

### CODE REVIEW

**Comment by keithpitt** [comment]
That's what I've been doing! 👍

**Comment by toolmantim** [comment]
Nice, but I've been putting them into `.buildkite/steps`

**Comment by toolmantim** [comment]
ala https://github.com/buildkite/polyglot-co-demo-lambda/tree/master/.buildkite and https://github.com/buildkite/polyglot-co-demo-backend/tree/master/.buildkite

**Comment by sj26** [comment]
Oic! Will move.

**Comment by sj26** [comment]
See 16a660f68ed924d3fbd2b9e8e44d68506de59b62 :-)

**Pull request merged**
