### PR TITLE
Default the agent to beta

### PR DESCRIPTION
**Pull request by lox**
Seeing as this is the advice I tend to give in the slack channel anyway, default the agent to beta. :rocket:

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
👌

**Comment by toolmantim** [comment]
I wonder if instead of these release channels, we should switch to "2.x" and "3.x" as the parameters? Because taking a step back, I think that's probably preferable for declaring dependencies of hooks, pipelines, etc. Same for people using our Docker image.

**Comment by gugahoi** [comment]
makes more sense to go to a specific version because when selecting `beta` in cloudformation I have no idea what version of the agent thats going to be. Also why not just release v3 stable 😝 ?

**Comment by toolmantim** [comment]
Also in that world, the elastic stack can always drop support for specific versions of Buildkite Agent too.

**Comment by lox** [comment]
I agree with all of the above, but that is a breaking change. I'm tempted to ship this in the 2.x series of the stack and then look to make the above change for v3.x?

**Pull request merged**
