### PR TITLE
Enable SSM access and disable SSH access.

### LINKED ISSUE #620: Proposal: Remove default external SSH access; default to SSM
This is an issue to track the discussion that started in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/598. 

Right now, SSH is open by default on Linux instances, but no such RDP access is made available for Windows. Ideally, we'd want access behavior to be consistent between the two platforms. 

There were two solutions thrown out in the PR linked above:
1. Open up RDP access by default on Windows
2. Remove SSH access from Linux and add SSM access to both platforms

It seems that consensus was moving towards option 2 at the time of issue creation.

### PR DESCRIPTION
**Pull request by xiaket**
1. Remove SSH keyname parameter and cleaned up a bunch of stuff.
2. Add minimal iam permissions to use SSM based access. Not using the `AmazonSSMManagedInstanceCore` as that will grant additional permission that are undesirable(`ssm:GetParameter` to `*` for example)

Fixes #620

### CODE REVIEW

**Comment by xiaket** [comment]
This will hopefully resolve #620

**Comment by ecktom** [comment]
Hi @xiaket, I guess we also need to have the `ssm-agent` running on the nodes, don't we?
```
    yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
    systemctl start amazon-ssm-agent
    systemctl enable amazon-ssm-agent
```

**Comment by jamesholmes-linktree** [comment]
Yes, but there's a way to do this more easily with the packer build: https://www.packer.io/docs/builders/amazon/instance#session-manager-connections

This will build the AMI with teh agent already installed.

**Comment by xiaket** [comment]
@ecktom Thanks Thomas! Am I right to believe that the ssm agent is included in Amazon Linux 2?

**Comment by ecktom** [comment]
@xiaket you're right, my bad. I got confused by the Amazon EKS optimized AMIs which are build on top of Amazon Linux 2 but do not include the ssm-agent by default ;)

**Comment by nitrocode** [comment]
Nice contribution! We've been using ssm to access the buildkite ec2 instances successfully as well.

For the uninitiated, it's been as simple as this.

```
brew cask install session-manager-plugin

aws ssm start-session --target i-aaabbbcccddd
```

**Review by chloeruka — APPROVED** [review]
Apologies for the delay in us thinking about this! SSH keys came up in conversation just recently so I'm going to put my ✅ on this, but before merging I'd be keen to grab some positive feels from @yob or @pda too.

**Pull request merged**
