### PR TITLE
Add correct cost tags to S3

### PR DESCRIPTION
**Pull request by hawkowl**
This PR:

- Adds the cost allocation tags to S3 buckets

### CODE REVIEW

**Comment by tduffield** [comment]
Whether or not the monitoring is enabled should be an option. We (personally) want it on :)

**Comment by lox** [comment]
Thanks for this @hawkowl, would be great to see this as two PR's, the first to fix the S3 cost tags and then an optional param for disabling instance detailed monitoring? Would be happy to have the latter default to off.

**Comment by hawkowl** [comment]
@lox Hi, this one is now just the correction of the S3 cost tags.

**Comment by lox** [comment]
Many thanks!

**Pull request merged**
