### PR TITLE
Bump buildkite agent to v3.22.1

### PR DESCRIPTION
**Pull request by sj26**
🥫

### CODE REVIEW

**Comment by sj26** [comment]
and backported to stable-4-5

**Comment by yob** [comment]
This updates the master branch, which currently isn't being released.

Do we need to update the 4-stable branch instead? Or maybe merge this and
then backport?

**Comment by sj26** [comment]
@yob I think I just beat you to it ;-)

**Comment by yob** [comment]
Our comments passed on their way through the tubes 🙃

**Pull request merged**
