### PR TITLE
Set InstanceRoleName as stack template output

### PR DESCRIPTION
**Pull request by dblandin**
We allow Buildkite agents to assume other IAM roles for certain deployment/operational actions. The role to be assumed needs to include the role ARN within its assume role policy.

It would be great to thread a dependency between the stack and the assume policy document via the stack output.

We use the existing `AutoScalingGroupName` stack output to create/update scheduled actions on the ASG and would like to use the role name to aid in other resources creation.

### CODE REVIEW

**Comment by lox** [comment]
Seems sensible, thanks @dblandin!

**Comment by dblandin** [comment]
@lox Thanks!! :100:

**Comment by arturopie** [comment]
Will this output return only the value of the parameter `InstanceRoleName`?
We don't set the `InstanceRoleName` parameter and let CloudFormation create the role for us. In our case, the `InstanceRoleName` output is empty.

**Comment by dblandin** [comment]
@arturopie Hmmm, I might have extracted the value in a suboptimal way.

I'm not too familar with the CloudFormation output syntax but it seems like we might want to reach into the created role and grab it's `RoleName` property instead.

https://github.com/buildkite/elastic-ci-stack-for-aws/blob/1bfa09d9fd6d35761ae0e5fad9b8081ff041a6dc/templates/buildkite-elastic.yml#L366-L369

**Comment by dblandin** [comment]
@arturopie Something like this? https://github.com/buildkite/elastic-ci-stack-for-aws/pull/428

Still need to check if that syntax is valid. Looks like the template is using a mix between the yaml and json function invocation styles.

**Comment by arturopie** [comment]
@dblandin something like that. I'm not sure about the syntax neither. it will need to be tested

**Pull request merged**
