### PR TITLE
Update docker & docker-compose

### PR DESCRIPTION
**Pull request by chloeruka**
For #689. Updating these docker dependencies is part of our regular release cycle.

Docker release notes  (19.03.2 > 19.03.12) 
https://docs.docker.com/engine/release-notes/

Compose release notes (moving from 1.25.1 > 1.26.2)
https://docs.docker.com/compose/release-notes/

### CODE REVIEW

**Comment by sj26** [comment]
We've been bitten by unexpected changes during Docker upgrades. Is there anything significant worth mentioning? Otherwise it's probably good to bump and then test it on edge.

**Comment by sj26** [comment]
(Scanning the release notes nothing stands out to me, although there are lots of security patches so 🏎💨)

**Comment by chloeruka** [comment]
> I'd like to think the keeping within the 19.03.xx series means we only get bug fixes. Right?

I'd like to hope so! Not every org follows semver as accurately as I'd like, but looking at the notes it looks to just be bugfixes for docker. docker-compose however does include a minor version bump, but looking at the changes it should be pretty low impact.

**Comment by DanielHeath** [comment]
Any way this could be a stack parameter for those who want to opt-in to newer versions?

I'd like to use the new 'target' feature in 1.27.x

**Comment by yob** [comment]
If it was a stack parameter, would that mean each instance downloads the requested version (if required) on boot?

I suspect we might be reluctant to slow down instance boot times, but it's certainly possible to do the download yourself in a [bootstrap script](https://github.com/buildkite/elastic-ci-stack-for-aws#customizing-instances-with-a-bootstrap-script).

In this particular case, we're aiming for a new release of the stack in the next week or two. Are you up for opening a PR to bump docker compose to 1.27.x? If so, we can sneak it in before the release.

**Comment by DanielHeath** [comment]
Ahh that makes sense. 

One option would be to make it a param in the docker-compose plugin (which downloads/reuses a different version if specified).

> In this particular case, we're aiming for a new release of the stack in the next week or two. Are you up for opening a PR to bump docker compose to 1.27.x? If so, we can sneak it in before the release.

Turns out I was experiencing some PEBKAC and no longer need the upgrade.

**Pull request merged**
